receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
